version: '3'
services:
    zookeeper1:
        image: confluentinc/cp-zookeeper
        container_name: zookeeper1
        network_mode: host
        environment: 
            - ZOOKEEPER_SERVER_ID=1
            - ZOOKEEPER_CLIENT_PORT=22181
            - ZOOKEEPER_SERVERS=localhost:22888:23888;localhost:32888:33888
            - ZOOKEEPER_TICK_TIME=2000
            - ZOOKEEPER_INIT_LIMIT=5
            - ZOOKEEPER_SYNC_LIMIT=2
    zookeeper2:
        image: confluentinc/cp-zookeeper
        container_name: zookeeper2
        network_mode: host
        environment: 
            - ZOOKEEPER_SERVER_ID=2
            - ZOOKEEPER_CLIENT_PORT=32181
            - ZOOKEEPER_SERVERS=localhost:22888:23888;localhost:32888:33888
            - ZOOKEEPER_TICK_TIME=2000
            - ZOOKEEPER_INIT_LIMIT=5
            - ZOOKEEPER_SYNC_LIMIT=2
    kafka1:
        image: confluentinc/cp-kafka
        container_name: kafka_broker1
        network_mode: host
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_ZOOKEEPER_CONNECT=localhost:22181,locahost:32181
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
        depends_on:
            - zookeeper1
            - zookeeper2
    kafka2:
        image: confluentinc/cp-kafka
        container_name: kafka_broker2
        network_mode: host
        environment:
            - KAFKA_BROKER_ID=2
            - KAFKA_ZOOKEEPER_CONNECT=localhost:22181,locahost:32181
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:19092
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
        depends_on:
            - zookeeper1
            - zookeeper2
    setup:
        image: komodoensis29/setup-kafka
        container_name: setup_kafka
        network_mode: host
        environment: 
            - KAFKA_CLUSTER_CONNECT=localhost:9092
            - LOAD_SAMPLE_DATA=True
        depends_on:
            - zookeeper1
            - zookeeper2
            - kafka1
            - kafka2
    consumer:
        image: komodoensis29/consumer-kafka
        container_name: consumer_kafka
        network_mode: host
        environment: 
            - KAFKA_CLUSTER_CONNECT=localhost:9092
        command: tail -F /dev/null
        depends_on:
            - zookeeper1
            - zookeeper2
            - kafka1
            - kafka2
            - setup